start-time: 2022-07-14 22:01:58.177580

Environment:
               test-name: GenerateInterface
            test-dirpath: /home/alain/Surelog/tests/GenerateInterface
           test-filepath: /home/alain/Surelog/tests/GenerateInterface/GenerateInterface.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface
     golden-log-filepath: /home/alain/Surelog/tests/GenerateInterface/GenerateInterface.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/GenerateInterface.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 4 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.178283
Loaded command line: top.sv  -writepp -parse -verbose -d uhdm -d ast -d inst -fileunit
Processed command line: top.sv -writepp -parse -verbose -d uhdm -d ast -d inst -fileunit -mt 0 -mp 0 -o ../NameCollisionBind/regression/GenerateInterface
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 'top.sv',
 '-writepp',
 '-parse',
 '-verbose',
 '-d',
 'uhdm',
 '-d',
 'ast',
 '-d',
 'inst',
 '-fileunit',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/GenerateInterface']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.194625 0:00:00.016342


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/GenerateInterface/GenerateInterface.log


Restoring pristine state ...
Found 4 files & directories


end-time: 2022-07-14 22:01:58.198180 0:00:00.020600
