start-time: 2022-07-14 22:01:58.235273

Environment:
               test-name: PragmaProtect
            test-dirpath: /home/alain/Surelog/tests/PragmaProtect
           test-filepath: /home/alain/Surelog/tests/PragmaProtect/PragmaProtect.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect
     golden-log-filepath: /home/alain/Surelog/tests/PragmaProtect/PragmaProtect.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/PragmaProtect.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 7 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.236013
Loaded command line: top.sv -d 0  +incdir+.  +libext+.v -writepp -filterprotected -parse
Processed command line: top.sv -d 0 +incdir+. +libext+.v -writepp -filterprotected -parse -mt 0 -mp 0 -o ../NameCollisionBind/regression/PragmaProtect
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 'top.sv',
 '-d',
 '0',
 '+incdir+.',
 '+libext+.v',
 '-writepp',
 '-filterprotected',
 '-parse',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/PragmaProtect']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.237459 0:00:00.001446


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/PragmaProtect/PragmaProtect.log


Restoring pristine state ...
Found 7 files & directories


end-time: 2022-07-14 22:01:58.237898 0:00:00.002625
