start-time: 2022-07-14 22:01:58.249095

Environment:
               test-name: PartSelectElab
            test-dirpath: /home/alain/Surelog/tests/PartSelectElab
           test-filepath: /home/alain/Surelog/tests/PartSelectElab/PartSelectElab.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab
     golden-log-filepath: /home/alain/Surelog/tests/PartSelectElab/PartSelectElab.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/PartSelectElab.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 4 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.249687
Loaded command line: -fileunit  -parse  -d uhdm -sv dut.sv -nobuiltin -nocache -elabuhdm
Processed command line: -fileunit -parse -d uhdm -sv dut.sv -nobuiltin -nocache -elabuhdm -mt 0 -mp 0 -o ../NameCollisionBind/regression/PartSelectElab
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 '-fileunit',
 '-parse',
 '-d',
 'uhdm',
 '-sv',
 'dut.sv',
 '-nobuiltin',
 '-nocache',
 '-elabuhdm',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/PartSelectElab']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.250856 0:00:00.001169


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/PartSelectElab/PartSelectElab.log


Restoring pristine state ...
Found 4 files & directories


end-time: 2022-07-14 22:01:58.251391 0:00:00.002296
